# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "amazing_print"
gem "rake"
gem "http"
gem "sxp"
gem "erb"
gem "irb"
