require "rubygems"
require "bundler/setup"

require_relative "lib/download"
require_relative "lib/extract"
require_relative "lib/generate"

task default: [:update]

task :download do
  Download.call(output: "dumb-jump.el")
end

task :extract do
  Extract.call(input: "dumb-jump.el", output: "dumb-jump-find-rules.el")
end

task :generate do
  Generate.call(input: "dumb-jump-find-rules.el", output: "dumb_jump.vim")
end

task :install do
  require "fileutils"

  FileUtils.chdir File.expand_path("..", __dir__) do
    FileUtils.cp("generator/dumb_jump.vim", "autoload/dumb_jump.vim", verbose: true)
  end
end

task update: [:download, :extract, :generate, :install] do
end
