require "rubygems"
require "bundler/setup"

require_relative "lib/download"
require_relative "lib/extract"
require_relative "lib/generate"

NAMESPACE = ENV.fetch("NAMESPACE", "zero#dumb_jump")

task default: [:update]

task :download do
  Download.call(output: "dumb-jump.el")
end

task :extract do
  Extract.call(input: "dumb-jump.el", output: "dumb-jump-find-rules.el")
end

task :generate do
  Generate.call(input: "dumb-jump-find-rules.el", output: "dumb_jump.vim", namespace: NAMESPACE)
end

task :install do
  require "fileutils"

  FileUtils.chdir(File.expand_path("..", __dir__), verbose: true) do
    filename = "autoload/#{NAMESPACE.gsub("#", "/")}.vim"
    FileUtils.mkdir_p("autoload/#{File.dirname(filename)}")
    FileUtils.cp("generator/dumb_jump.vim", filename, verbose: true)
  end
end

task build: [:download, :extract, :generate, :install]

task update: [:build]
