require "rubygems"
require "bundler/setup"

require_relative "lib/download"
require_relative "lib/extract"
require_relative "lib/generate_dumb_jump"
require_relative "lib/generate_filetype"

task default: [:update]

task :download do
  Download.call(output: "dumb-jump.el")
end

task :extract do
  input = "dumb-jump.el"
  Rake::Task["download"].invoke unless File.exist?(input)
  Extract.call(input: input, output: "dumb-jump-find-rules.el")
end

task generate: ["generate:dumb_jump"]

namespace :generate do
  task :dumb_jump do
    input = "dumb-jump-find-rules.el"
    Rake::Task["extract"].invoke unless File.exist?(input)
    GenerateDumbJump.call(input: input)
  end

  task :filetype do
    GenerateFiletype.call
  end
end

task build: [:download, :extract, :"generate:dumb_jump"]

task update: [:build]
